low = ["traitor", "florida_man", "paradox_clone", "cortical_borer", "obsessed"]
medium = ["heretic", "bloodsucker", "changeling", "revenant", "nightmare", "slasher", "traitor/contractor", "abductor/scientist/onemanteam", "bingle"]
high = ["cult", "wizard", "clock_cultist", "ninja", "cortical_borer/hivemind", "blob", "darkspawn", "bloodling"]
